### ISSUE TITLE
CodeMirror not found in "CodeMirror/"

### ISSUE THREAD

**Issue by castaf** [Kotti/kotti_tinymce#31]
When we click "View > Source code" the code editor does not be launched. The browser fails to load :
- /fanstatic/kotti_tinymce/plugins/codemirror/CodeMirror/lib/codemirror.css
- /fanstatic/kotti_tinymce/plugins/codemirror/CodeMirror/lib/codemirror.js

Seems there are wrong paths in source.html of the codemirror plugin.

**Comment by disko** [comment]
Fixed in f46016754930f2c2dceee1a9bbfd81973003092f and released as 0.7.1.
